---
name: Dependency Check

on:
  workflow_call:

jobs:
  
  code-dependency:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
        
      - name: Verify Java
        run: |
          echo $JAVA_HOME
          java -version
    
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
            JAVA_HOME: /opt/jdk
        with:
          project: "bankapp"
          path: "."
          format: "HTML"
          out: "reports"

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports